favorite_word = "Krankenversicherungbeitragsrückerstattung"
print(favorite_word)
'''
Select the first letter of the variable my_name and save it to first_initial.
'''
my_name = "Dmytrii Demidas"
first_initial = my_name[0]

'''
You’re a programmer working for Copeland’s Corporate Company. At this company, each employee’s user name is generated by taking the first five letters of their last name.

A new employee, Rodrigo Villanueva, is starting today and you need to create his account. His first_name and last_name are stored as strings in script.py.

Create a variable new_account by slicing the first five letters of his last_name.
'''
'''
Temporary passwords for new employees are also generated from their last names.

Create a variable called temp_password by creating a slice out of the third through sixth letters of last_name. Your string should have a total of 4 characters.
'''
first_name = "Rodrigo"
last_name = "Villanueva"
new_account = last_name[:5]
print(new_account)
temp_password = last_name[2:6]
print(temp_password)

'''
Write a function called account_generator() that takes two inputs, first_name and last_name and concatenates the first three letters of each and then returns the new account name.
'''
'''
Test your function on the first_name and last_name provided in script.py and save it to the variable new_account.
'''
first_name = "Julie"
last_name = "Blevins"

def account_generator(first_name, last_name):
  account_name = (first_name[:3]) + (last_name[:3])
  return account_name

new_account = account_generator(first_name, last_name)
print(new_account)

'''
Write a function called password_generator() that takes two inputs, first_name and last_name, and then concatenates the last three letters of each and returns them as a string.
'''
first_name = "Reiko"
last_name = "Matsuki"

favorite_fruit = "blueberry"
length = len(favorite_fruit)
print(length)
# Output: 9
last_char = favorite_fruit[len(favorite_fruit)-1]
print(last_char)
# Output: y

def password_generator(first_name, last_name):
  f_temp_password = ((first_name[len(first_name)-3:])+(last_name[len(last_name)-3:]))
  return f_temp_password

password_generator(first_name, last_name)

temp_password = (password_generator(first_name, last_name))
print(temp_password)

'''
Use negative indices to find the second to last character in company_motto. Save this to the variable second_to_last.
'''
'''
Use negative indices to create a slice of the last 4 characters in company_motto. Save this to the variable final_word.
'''
company_motto = "Copeland's Corporate Company helps you capably cope with the constant cacophony of daily life"
second_to_last = company_motto[-2]
print(second_to_last)
final_word = company_motto[-4:]
print(final_word)

'''
Then, concatenate the string "R" with a slice of first_name that includes everything but the first character, "B", and save it to a new string fixed_first_name.
'''
first_name = "Bob"
last_name = "Daily"

fixed_first_name = "R" + first_name[1:]
print(fixed_first_name)

'''
This function is checking if the given word contains UMLAUT letters:
'''
#word = "Dzygurda"
word = "Krankenversicherungbeitragsrückerstattung"
word = word.lower()

def letter_check(word):
  f_bool_checker = False
  for character in word:
    if character == "ä":
      f_bool_checker = True
    elif character == "ü":
      f_bool_checker = True
    elif character == "ö":
      f_bool_checker = True
  return f_bool_checker

bool_checker = letter_check(word)
print("Your favorite word "+ word + " contains UMLAUT characters: " + str(bool_checker))
#print(bool_checker)

'''
Write a function called letter_check that takes two inputs, word and letter.
This function should return True if the word contains the letter and False if it does not.
'''
'''
This option is more stupid just to fit criteria of Codeacademy engine
'''
def letter_check(word,letter):
  word = word.lower()
  f_bool_checker = False
  for character in word:
    if character == letter:
      f_bool_checker = True
  return f_bool_checker

#bool_checker = letter_check(word,letter)
#print("Your favorite word "+ word + " contains UMLAUT characters: " + str(bool_checker))
print(letter_check("strawberry", "a"))
print(letter_check("strawberry", "o"))

'''
Write a function called contains that takes two arguments, big_string and little_string and returns True if big_string contains little_string.

For example contains("watermelon", "melon") should return True and contains("watermelon", "berry") should return False.
'''
'''
Write a function called common_letters that takes two arguments, string_one and string_two and then returns a list with all of the letters they have in common.

The letters in the returned list should be unique. For example,

common_letters("banana", "cream")

Copy to Clipboard

should return ['a'].
'''
def contains(big_string, little_string):
  bool_checker = (little_string in big_string)
  return bool_checker

print(contains("watermelon","melon"))

def common_letters(string_one,string_two):
  l_common_letters = []
  
  for letter in string_one:
    if ((letter in string_two) and (letter not in l_common_letters)) == True:
      l_common_letters.append(letter)
  
  return l_common_letters

  print(common_letters("banana","cream"))
  
'''
Let’s start with username_generator. Create a function called username_generator take two inputs, first_name and last_name and returns a user_name. The username should be a slice of the first three letters of their first name and the first four letters of their last name. If their first name is less than three letters or their last name is less than four letters it should use their entire names.

For example, if the employee’s name is Abe Simpson the function should generate the username AbeSimp.
'''
'''
Great work! Now for the temporary password, they want the function to take the input user name and shift all of the letters by one to the right, so the last letter of the username ends up as the first letter and so forth. For example, if the username is AbeSimp, then the temporary password generated should be pAbeSim.

Start by defining a function called password_generator that takes one parameter user_name and defines an empty string named password within the function body.
'''
'''
Inside password_generator, create a for loop that iterates through the indices of user_name by going from 0 to len(user_name).

The loop should create the password by shifting all the letters of user_name one to the right. To do so, add the letter at the previous index of user_name to password with each pass of the loop.

After the for loop but still within the definition of password_generator, return the password.
'''

#solution without strict checks
def username_generator(first_name, last_name):
  f_user_name = (first_name[0:3]+last_name[0:4])
  return f_user_name

user_name = username_generator("Abe","Simpson")
print(user_name)

def password_generator(user_name):
  password = ((user_name[-1])+(user_name[:-1]))
  return password

user_password = password_generator(user_name)
print(user_password)
#solution which performs all naming policy checks:
def username_generator(first_name, last_name):
    if len(first_name) < 3:
        user_name = first_name
    else:
        user_name = first_name[0:3]
    if len(last_name) < 4:
        user_name += last_name
    else:
        user_name += last_name[0:4]
    return user_name
  
user_name = username_generator("Abe","Simpson")
print(user_name)   

def password_generator(user_name):
    password = ""
    for i in range(0, len(user_name)):
        password += user_name[i-1]
    return password
user_password = password_generator(user_name)
print(user_password)